import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Albert_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Albert_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ELECTO || Electronics Store",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header />
        {children}</body>
    </html>
  );
}